on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - run: |
          ftp -n -v -p "${{secrets.FTP_HOST}}" <<EOF
          user ${{secrets.FTP_USER}} ${{secrets.FTP_PASSWORD}}
          cd public_html
          put index.html
          EOF
