on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FTP_USER: "${{secrets.FTP_USER}}"
      FTP_PASSWORD: "${{secrets.FTP_PASSWORD}}"
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - run: |
          ftp -?
